import { forwardRef, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, type TextareaHTMLAttributes } from 'react';
import { LoaderCircle } from 'lucide-react';

const cls = (...classes: Array<string | false | undefined>) => classes.filter(Boolean).join(' ');
export function Card({ children, className }: { children: ReactNode; className?: string }) { return <section className={cls('rounded-xl border border-slate-200 bg-white shadow-panel', className)}>{children}</section>; }
export function Button({ className, variant = 'primary', loading, children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'danger' | 'ghost'; loading?: boolean }) { const variants = { primary: 'bg-brand text-white hover:bg-sky-700 focus:ring-brand', secondary: 'border border-slate-300 bg-white text-ink hover:bg-slate-50 focus:ring-slate-300', danger: 'bg-red-600 text-white hover:bg-red-700 focus:ring-red-500', ghost: 'text-slate-600 hover:bg-slate-100 focus:ring-slate-300' }; return <button className={cls('inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-4 text-sm font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-60', variants[variant], className)} disabled={loading || props.disabled} {...props}>{loading && <LoaderCircle className="h-4 w-4 animate-spin" />}{children}</button>; }
export const Input = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(({ className, ...props }, ref) => <input ref={ref} className={cls('h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm text-ink outline-none transition focus:border-brand focus:ring-2 focus:ring-blue-100 disabled:bg-slate-50', className)} {...props} />); Input.displayName = 'Input';
export const Select = forwardRef<HTMLSelectElement, SelectHTMLAttributes<HTMLSelectElement>>(({ className, ...props }, ref) => <select ref={ref} className={cls('h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm text-ink outline-none transition focus:border-brand focus:ring-2 focus:ring-blue-100', className)} {...props} />); Select.displayName = 'Select';
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaHTMLAttributes<HTMLTextAreaElement>>(({ className, ...props }, ref) => <textarea ref={ref} className={cls('min-h-28 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-ink outline-none transition focus:border-brand focus:ring-2 focus:ring-blue-100', className)} {...props} />); Textarea.displayName = 'Textarea';
export function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="block space-y-1.5"><span className="text-sm font-medium text-ink">{label}</span>{children}{error && <span className="block text-xs text-red-600">{error}</span>}</label>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="px-6 py-16 text-center"><p className="font-semibold text-ink">{title}</p><p className="mt-1 text-sm text-slate-500">{description}</p></div>; }
export function PageLoader() { return <div className="grid min-h-screen place-items-center bg-mist"><LoaderCircle className="h-8 w-8 animate-spin text-brand" /></div>; }
