import { useState } from 'react';
import { BarChart3, ClipboardList, FilePlus2, LogOut, Menu, ShieldCheck, Users, UserRound } from 'lucide-react';
import { Link, NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext'; import type { Role } from '@/types';

const menu: Array<{ label: string; to: string; icon: typeof BarChart3; roles: Role[] }> = [
  { label: 'Dashboard', to: '/dashboard', icon: BarChart3, roles: ['ADMIN', 'CUSTOMER', 'CLAIM_AGENT', 'INVESTIGATOR', 'SUPERVISOR'] },
  { label: 'My claims', to: '/claims', icon: ClipboardList, roles: ['CUSTOMER'] },
  { label: 'New claim', to: '/claims/new', icon: FilePlus2, roles: ['CUSTOMER'] },
  { label: 'Work queue', to: '/work-queue', icon: ClipboardList, roles: ['CLAIM_AGENT', 'INVESTIGATOR', 'SUPERVISOR'] },
  { label: 'User management', to: '/users', icon: Users, roles: ['ADMIN'] },
  { label: 'All claims', to: '/admin/claims', icon: ClipboardList, roles: ['ADMIN'] }
];
function Sidebar({ close }: { close?: () => void }) { const { session, logout } = useAuth(); const navigate = useNavigate(); if (!session) return null; const links = menu.filter((item) => item.roles.includes(session.role)); return <aside className="flex h-full w-72 flex-col bg-navy px-4 py-5 text-white"><Link to="/dashboard" className="flex items-center gap-3 px-3 py-2"><span className="grid h-9 w-9 place-items-center rounded-lg bg-sky-500 font-bold text-white">CF</span><span><strong className="block tracking-tight text-white">ClaimFlow</strong><small className="text-xs text-slate-300">Insurance operations</small></span></Link><nav className="mt-8 flex-1 space-y-1">{links.map(({ label, to, icon: Icon }) => <NavLink key={to} to={to} onClick={close} className={({ isActive }) => `flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold transition ${isActive ? 'bg-white/20 text-white' : 'text-slate-200 hover:bg-white/10 hover:text-white'}`}><Icon className="h-5 w-5" />{label}</NavLink>)}</nav><div className="border-t border-white/20 pt-4"><div className="mb-3 px-3"><p className="truncate text-sm font-semibold text-white">{session.firstName} {session.lastName}</p><p className="text-xs font-medium text-slate-300">{session.role.replace('_', ' ')}</p></div><button onClick={() => { logout(); navigate('/login'); }} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-slate-200 hover:bg-white/10 hover:text-white"><LogOut className="h-5 w-5" />Sign out</button></div></aside>; }
export function AppLayout() { const [open, setOpen] = useState(false); const location = useLocation(); return <div className="min-h-screen bg-mist"><div className="fixed inset-y-0 left-0 z-30 hidden lg:block"><Sidebar /></div>{open && <div className="fixed inset-0 z-40 lg:hidden"><button aria-label="Close navigation" className="absolute inset-0 bg-slate-950/45" onClick={() => setOpen(false)} /><div className="relative h-full"><Sidebar close={() => setOpen(false)} /></div></div>}<main className="lg:pl-72"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-slate-200 bg-white/95 px-4 backdrop-blur lg:px-8"><button className="rounded-md p-2 text-slate-600 lg:hidden" aria-label="Open navigation" onClick={() => setOpen(true)}><Menu className="h-5 w-5" /></button><div className="hidden items-center gap-2 text-sm text-slate-600 sm:flex"><ShieldCheck className="h-4 w-4 text-emerald-600" />Secure claim operations</div><Link to="/profile" className="flex items-center gap-2 rounded-full border border-slate-200 bg-white py-1 pl-1 pr-3 text-sm font-semibold text-ink shadow-sm"><span className="grid h-8 w-8 place-items-center rounded-full bg-brand text-white" aria-hidden="true"><UserRound className="h-4 w-4" /></span><span>Profile</span></Link></header><div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8"><div className="mb-5 flex items-center gap-2 text-xs text-slate-400"><span>ClaimFlow</span><span>/</span><span className="capitalize text-slate-600">{location.pathname.split('/').filter(Boolean).at(-1)?.replaceAll('-', ' ') ?? 'dashboard'}</span></div><Outlet /></div></main></div>; }
